site_name: Lyrasis CST Interoperability Project
site_description: Developing enhancements for Lyrasis Community-Supported Technologies.
site_url: https://lyrasisorghome.github.io/InteroperabilityProject
repo_url: https://github.com/lyrasisorghome/InteroperabilityProject
nav:
  - Home: index.md
  - Get Involved: feedback.md
  - About: about.md

theme: readthedocs
plugins:
  - rss